//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRevision.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttemptedExam
    {
        public int AttemptedId { get; set; }
        public Nullable<int> QuesType { get; set; }
        public Nullable<int> QuestionSetId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string QuestionAnswers { get; set; }
        public Nullable<int> Status { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    }
}
