//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRevision.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineRevisionEntities : DbContext
    {
        public OnlineRevisionEntities()
            : base("name=OnlineRevisionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<AttemptedExam> AttemptedExam { get; set; }
        public virtual DbSet<Explanation> Explanation { get; set; }
        public virtual DbSet<PaymentDetails> PaymentDetails { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<QuestionSet> QuestionSet { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<SampleTable> SampleTable { get; set; }
        public virtual DbSet<StudentResults> StudentResults { get; set; }
        public virtual DbSet<StudySection> StudySection { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TrackUsers> TrackUsers { get; set; }
        public virtual DbSet<UserDetails> UserDetails { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<Folders> Folders { get; set; }
    }
}
