//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRevision.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetails
    {
        public int Id { get; set; }
        public string PaymentId { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public string Details { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
