//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRevision.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int Id { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public Nullable<int> QuestionSetId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string QuestionName { get; set; }
        public string Options { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
