//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRevision.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleTable
    {
        public int Id { get; set; }
        public string QuestionName { get; set; }
        public string Options { get; set; }
        public string QuestionAnswers { get; set; }
    }
}
