//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRevision.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackUsers
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Activity { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
    }
}
